Uhh

diff --git a/.config/zsh/functions/vifxn b/.config/zsh/functions/vifxn
--- a/.config/zsh/functions/vifxn
+++ b/.config/zsh/functions/vifxn
@@ -1,30 +1,47 @@
 # Edit the file that a shell function is defined in
 local -r func_name="${1:?}"
+
 local type
 type="$(type "${func_name}")"
+
+# Ensure we have a shell function
 if ! grep -q "shell function" <<< "${type}"; then
-  log::err "Function does not exist | func_name='$func_name' type='${type}'"
+  log::err "Function does not exist | func_name='${func_name}'"
+  log::warn "type ${func_name}='$(type "${func_name}")'"
   return 1
 fi
 
-# Find the file the function is in
+# Find the file our program lives in:
+# * autoload (we have to search) or
+# * already loaded (loaded autoload OR plugin)
 local file
 if grep -q "is an autoload shell function" <<< "${type}"; then
-  for autoload_file in "${fpath[@]}"; do
-    local maybe_file="${autoload_file}/${func_name}"
-    [ -f "${maybe_file}" ] || continue
-    file="${maybe_file}"
-    log::info "Found autoload function | func_name='${func_name}' file='${file}'"
-    break
+  # Search through '$fpath' to find the function and open it
+  local dir
+  for dir in "${fpath[@]}"; do
+    [ -f "${dir}/${func_name}" ] || continue
+    file="$dir/$func_name"
   done
 else
   file="$(awk '{print $NF}' <<< "${type}")"
 fi
 
-# Set editor args: Jump to the function definition. If it's an autoloaded
-# function then there's nothing to do here
+# Helper function just to increase semantic meaning of code
+function _is_autoload_function() {
+  local file="${1:?}"
+  grep -q "\/functions\/" <<< "${file}"
+}
+
+# If it's not an autoload function, then try to jump to the function definition.
+# Autoloaded functions don't have 'function $func_name() {' at the top so we
+# don't try to do anything for them
 local editor_args=()
-if grep -q "\/functions\/" <<< "${type}"; then
-  editor_args=("+/${func_name} () {")
+if ! _is_autoload_function "${file}"; then
+  editor_args+=(+"/\<\zs${func_name}\ze() {$")
 fi
-"${EDITOR}" "${editor_args[@]}" "${file}"
+
+# Finally: Open the editor
+run_cmd "$EDITOR" "${editor_args[@]}" "$file"
+
+# Clean up
+unset -f _is_autoload_function
