Added 'pubkey ssh'. Moved 'branchlog'
* Moved 'git_branchlog' to 'git-branchlog' so 'git branchlog' works outta the box

diff --git a/.config/git/template/hooks/pre-commit b/.config/git/template/hooks/pre-commit
--- a/.config/git/template/hooks/pre-commit
+++ b/.config/git/template/hooks/pre-commit
@@ -55,8 +55,8 @@ function trailing_whitespace() {
 
 function main() {
   if ! source "$HOME/.config/bash-init/log.sh" &>/dev/null; then
-    function log::info { echo "[INFO] $@"; }
-    function log::err { echo "[ERROR] $@"; }
+    function log::info { echo "[INFO] $@" >&2; }
+    function log::err { echo "[ERROR] $@" >&2; }
   fi
 
   # Preflight check
diff --git a/.config/git/template/hooks/prepare-commit-msg b/.config/git/template/hooks/prepare-commit-msg
--- a/.config/git/template/hooks/prepare-commit-msg
+++ b/.config/git/template/hooks/prepare-commit-msg
@@ -26,8 +26,8 @@ function append() {
 
 function main() {
   if ! source "$HOME/.config/bash-init/log.sh" &>/dev/null; then
-    function log::info { echo "[INFO] $@"; }
-    function log::err { echo "[ERROR] $@"; }
+    function log::info { echo "[INFO] $@" >&2; }
+    function log::err { echo "[ERROR] $@" >&2; }
   fi
 
   # https://www.atlassian.com/git/tutorials/git-hooks
